name: Build and Deploy Code

on: [push, pull_request]
env:
  APP_ENV: development
  APP_MONGO_USER: test
  APP_MONGO_PASS: password
  APP_MONGO_DB: test
jobs:
  job1:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_USER}
          MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_PASS}
          MONGO_INITDB_DATABASE: ${APP_MONGO_DB}
        ports:
          - 27017:27017
    steps:
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest